# action.yml
name: 'Run Naturaldocs'
description: 'Run naturaldocs'
inputs:
  output-dir:  # id of input
    description: 'Output directory for naturaldocs'
    required: true
    default: '.'
  project-config-dir:  # id of input
    description: 'Relative path to the project configuration folder'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project-config-dir }}
    - ${{ inputs.output-dir }}